/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppRouteImport } from './routes/_app'
import { Route as AppActivityRouteImport } from './routes/_app/activity'
import { Route as AppAuditLogsRouteImport } from './routes/_app/audit-logs'
import { Route as AppDashboardRouteImport } from './routes/_app/dashboard'
import { Route as AppDiagnosticsRouteImport } from './routes/_app/diagnostics'
import { Route as AppDocumentationRouteImport } from './routes/_app/documentation'
import { Route as AppMonitoringRouteImport } from './routes/_app/monitoring'
import { Route as AppNetworksRouteImport } from './routes/_app/networks'
import { Route as AppRemoteDevicesRouteImport } from './routes/_app/remote-devices'
import { Route as AppSettingsRouteImport } from './routes/_app/settings'
import { Route as AppTopologyRouteImport } from './routes/_app/topology'
import { Route as AppDevicesIdRouteImport } from './routes/_app/devices/$id'
import { Route as AppProjectsApplicationSecurityRouteImport } from './routes/_app/projects/application-security'
import { Route as AppProjectsAuthenticationRouteImport } from './routes/_app/projects/authentication'
import { Route as AppProjectsIpRangeScannerRouteImport } from './routes/_app/projects/ip-range-scanner'
import { Route as AppProjectsPortScannerRouteImport } from './routes/_app/projects/port-scanner'
import { Route as AppProjectsSubdomainEnumerationRouteImport } from './routes/_app/projects/subdomain-enumeration'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const AppActivityRoute = AppActivityRouteImport.update({
  id: '/activity',
  path: '/activity',
  getParentRoute: () => AppRoute,
} as any)
const AppAuditLogsRoute = AppAuditLogsRouteImport.update({
  id: '/audit-logs',
  path: '/audit-logs',
  getParentRoute: () => AppRoute,
} as any)
const AppDashboardRoute = AppDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AppRoute,
} as any)
const AppDiagnosticsRoute = AppDiagnosticsRouteImport.update({
  id: '/diagnostics',
  path: '/diagnostics',
  getParentRoute: () => AppRoute,
} as any)
const AppDocumentationRoute = AppDocumentationRouteImport.update({
  id: '/documentation',
  path: '/documentation',
  getParentRoute: () => AppRoute,
} as any)
const AppMonitoringRoute = AppMonitoringRouteImport.update({
  id: '/monitoring',
  path: '/monitoring',
  getParentRoute: () => AppRoute,
} as any)
const AppNetworksRoute = AppNetworksRouteImport.update({
  id: '/networks',
  path: '/networks',
  getParentRoute: () => AppRoute,
} as any)
const AppRemoteDevicesRoute = AppRemoteDevicesRouteImport.update({
  id: '/remote-devices',
  path: '/remote-devices',
  getParentRoute: () => AppRoute,
} as any)
const AppSettingsRoute = AppSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AppRoute,
} as any)
const AppTopologyRoute = AppTopologyRouteImport.update({
  id: '/topology',
  path: '/topology',
  getParentRoute: () => AppRoute,
} as any)
const AppDevicesIdRoute = AppDevicesIdRouteImport.update({
  id: '/devices/$id',
  path: '/devices/$id',
  getParentRoute: () => AppRoute,
} as any)
const AppProjectsApplicationSecurityRoute =
  AppProjectsApplicationSecurityRouteImport.update({
    id: '/projects/application-security',
    path: '/projects/application-security',
    getParentRoute: () => AppRoute,
  } as any)
const AppProjectsAuthenticationRoute =
  AppProjectsAuthenticationRouteImport.update({
    id: '/projects/authentication',
    path: '/projects/authentication',
    getParentRoute: () => AppRoute,
  } as any)
const AppProjectsIpRangeScannerRoute =
  AppProjectsIpRangeScannerRouteImport.update({
    id: '/projects/ip-range-scanner',
    path: '/projects/ip-range-scanner',
    getParentRoute: () => AppRoute,
  } as any)
const AppProjectsPortScannerRoute = AppProjectsPortScannerRouteImport.update({
  id: '/projects/port-scanner',
  path: '/projects/port-scanner',
  getParentRoute: () => AppRoute,
} as any)
const AppProjectsSubdomainEnumerationRoute =
  AppProjectsSubdomainEnumerationRouteImport.update({
    id: '/projects/subdomain-enumeration',
    path: '/projects/subdomain-enumeration',
    getParentRoute: () => AppRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/activity': typeof AppActivityRoute
  '/audit-logs': typeof AppAuditLogsRoute
  '/dashboard': typeof AppDashboardRoute
  '/diagnostics': typeof AppDiagnosticsRoute
  '/documentation': typeof AppDocumentationRoute
  '/monitoring': typeof AppMonitoringRoute
  '/networks': typeof AppNetworksRoute
  '/remote-devices': typeof AppRemoteDevicesRoute
  '/settings': typeof AppSettingsRoute
  '/topology': typeof AppTopologyRoute
  '/devices/$id': typeof AppDevicesIdRoute
  '/projects/application-security': typeof AppProjectsApplicationSecurityRoute
  '/projects/authentication': typeof AppProjectsAuthenticationRoute
  '/projects/ip-range-scanner': typeof AppProjectsIpRangeScannerRoute
  '/projects/port-scanner': typeof AppProjectsPortScannerRoute
  '/projects/subdomain-enumeration': typeof AppProjectsSubdomainEnumerationRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/activity': typeof AppActivityRoute
  '/audit-logs': typeof AppAuditLogsRoute
  '/dashboard': typeof AppDashboardRoute
  '/diagnostics': typeof AppDiagnosticsRoute
  '/documentation': typeof AppDocumentationRoute
  '/monitoring': typeof AppMonitoringRoute
  '/networks': typeof AppNetworksRoute
  '/remote-devices': typeof AppRemoteDevicesRoute
  '/settings': typeof AppSettingsRoute
  '/topology': typeof AppTopologyRoute
  '/devices/$id': typeof AppDevicesIdRoute
  '/projects/application-security': typeof AppProjectsApplicationSecurityRoute
  '/projects/authentication': typeof AppProjectsAuthenticationRoute
  '/projects/ip-range-scanner': typeof AppProjectsIpRangeScannerRoute
  '/projects/port-scanner': typeof AppProjectsPortScannerRoute
  '/projects/subdomain-enumeration': typeof AppProjectsSubdomainEnumerationRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_app': typeof AppRouteWithChildren
  '/_app/activity': typeof AppActivityRoute
  '/_app/audit-logs': typeof AppAuditLogsRoute
  '/_app/dashboard': typeof AppDashboardRoute
  '/_app/diagnostics': typeof AppDiagnosticsRoute
  '/_app/documentation': typeof AppDocumentationRoute
  '/_app/monitoring': typeof AppMonitoringRoute
  '/_app/networks': typeof AppNetworksRoute
  '/_app/remote-devices': typeof AppRemoteDevicesRoute
  '/_app/settings': typeof AppSettingsRoute
  '/_app/topology': typeof AppTopologyRoute
  '/_app/devices/$id': typeof AppDevicesIdRoute
  '/_app/projects/application-security': typeof AppProjectsApplicationSecurityRoute
  '/_app/projects/authentication': typeof AppProjectsAuthenticationRoute
  '/_app/projects/ip-range-scanner': typeof AppProjectsIpRangeScannerRoute
  '/_app/projects/port-scanner': typeof AppProjectsPortScannerRoute
  '/_app/projects/subdomain-enumeration': typeof AppProjectsSubdomainEnumerationRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/activity'
    | '/audit-logs'
    | '/dashboard'
    | '/diagnostics'
    | '/documentation'
    | '/monitoring'
    | '/networks'
    | '/remote-devices'
    | '/settings'
    | '/topology'
    | '/devices/$id'
    | '/projects/application-security'
    | '/projects/authentication'
    | '/projects/ip-range-scanner'
    | '/projects/port-scanner'
    | '/projects/subdomain-enumeration'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/activity'
    | '/audit-logs'
    | '/dashboard'
    | '/diagnostics'
    | '/documentation'
    | '/monitoring'
    | '/networks'
    | '/remote-devices'
    | '/settings'
    | '/topology'
    | '/devices/$id'
    | '/projects/application-security'
    | '/projects/authentication'
    | '/projects/ip-range-scanner'
    | '/projects/port-scanner'
    | '/projects/subdomain-enumeration'
  id:
    | '__root__'
    | '/'
    | '/_app'
    | '/_app/activity'
    | '/_app/audit-logs'
    | '/_app/dashboard'
    | '/_app/diagnostics'
    | '/_app/documentation'
    | '/_app/monitoring'
    | '/_app/networks'
    | '/_app/remote-devices'
    | '/_app/settings'
    | '/_app/topology'
    | '/_app/devices/$id'
    | '/_app/projects/application-security'
    | '/_app/projects/authentication'
    | '/_app/projects/ip-range-scanner'
    | '/_app/projects/port-scanner'
    | '/_app/projects/subdomain-enumeration'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/activity': {
      id: '/_app/activity'
      path: '/activity'
      fullPath: '/activity'
      preLoaderRoute: typeof AppActivityRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/audit-logs': {
      id: '/_app/audit-logs'
      path: '/audit-logs'
      fullPath: '/audit-logs'
      preLoaderRoute: typeof AppAuditLogsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/dashboard': {
      id: '/_app/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AppDashboardRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/diagnostics': {
      id: '/_app/diagnostics'
      path: '/diagnostics'
      fullPath: '/diagnostics'
      preLoaderRoute: typeof AppDiagnosticsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/documentation': {
      id: '/_app/documentation'
      path: '/documentation'
      fullPath: '/documentation'
      preLoaderRoute: typeof AppDocumentationRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/monitoring': {
      id: '/_app/monitoring'
      path: '/monitoring'
      fullPath: '/monitoring'
      preLoaderRoute: typeof AppMonitoringRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/networks': {
      id: '/_app/networks'
      path: '/networks'
      fullPath: '/networks'
      preLoaderRoute: typeof AppNetworksRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/remote-devices': {
      id: '/_app/remote-devices'
      path: '/remote-devices'
      fullPath: '/remote-devices'
      preLoaderRoute: typeof AppRemoteDevicesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/settings': {
      id: '/_app/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AppSettingsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/topology': {
      id: '/_app/topology'
      path: '/topology'
      fullPath: '/topology'
      preLoaderRoute: typeof AppTopologyRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/devices/$id': {
      id: '/_app/devices/$id'
      path: '/devices/$id'
      fullPath: '/devices/$id'
      preLoaderRoute: typeof AppDevicesIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/projects/application-security': {
      id: '/_app/projects/application-security'
      path: '/projects/application-security'
      fullPath: '/projects/application-security'
      preLoaderRoute: typeof AppProjectsApplicationSecurityRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/projects/authentication': {
      id: '/_app/projects/authentication'
      path: '/projects/authentication'
      fullPath: '/projects/authentication'
      preLoaderRoute: typeof AppProjectsAuthenticationRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/projects/ip-range-scanner': {
      id: '/_app/projects/ip-range-scanner'
      path: '/projects/ip-range-scanner'
      fullPath: '/projects/ip-range-scanner'
      preLoaderRoute: typeof AppProjectsIpRangeScannerRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/projects/port-scanner': {
      id: '/_app/projects/port-scanner'
      path: '/projects/port-scanner'
      fullPath: '/projects/port-scanner'
      preLoaderRoute: typeof AppProjectsPortScannerRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/projects/subdomain-enumeration': {
      id: '/_app/projects/subdomain-enumeration'
      path: '/projects/subdomain-enumeration'
      fullPath: '/projects/subdomain-enumeration'
      preLoaderRoute: typeof AppProjectsSubdomainEnumerationRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppRouteChildren {
  AppActivityRoute: typeof AppActivityRoute
  AppAuditLogsRoute: typeof AppAuditLogsRoute
  AppDashboardRoute: typeof AppDashboardRoute
  AppDiagnosticsRoute: typeof AppDiagnosticsRoute
  AppDocumentationRoute: typeof AppDocumentationRoute
  AppMonitoringRoute: typeof AppMonitoringRoute
  AppNetworksRoute: typeof AppNetworksRoute
  AppRemoteDevicesRoute: typeof AppRemoteDevicesRoute
  AppSettingsRoute: typeof AppSettingsRoute
  AppTopologyRoute: typeof AppTopologyRoute
  AppDevicesIdRoute: typeof AppDevicesIdRoute
  AppProjectsApplicationSecurityRoute: typeof AppProjectsApplicationSecurityRoute
  AppProjectsAuthenticationRoute: typeof AppProjectsAuthenticationRoute
  AppProjectsIpRangeScannerRoute: typeof AppProjectsIpRangeScannerRoute
  AppProjectsPortScannerRoute: typeof AppProjectsPortScannerRoute
  AppProjectsSubdomainEnumerationRoute: typeof AppProjectsSubdomainEnumerationRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppActivityRoute: AppActivityRoute,
  AppAuditLogsRoute: AppAuditLogsRoute,
  AppDashboardRoute: AppDashboardRoute,
  AppDiagnosticsRoute: AppDiagnosticsRoute,
  AppDocumentationRoute: AppDocumentationRoute,
  AppMonitoringRoute: AppMonitoringRoute,
  AppNetworksRoute: AppNetworksRoute,
  AppRemoteDevicesRoute: AppRemoteDevicesRoute,
  AppSettingsRoute: AppSettingsRoute,
  AppTopologyRoute: AppTopologyRoute,
  AppDevicesIdRoute: AppDevicesIdRoute,
  AppProjectsApplicationSecurityRoute: AppProjectsApplicationSecurityRoute,
  AppProjectsAuthenticationRoute: AppProjectsAuthenticationRoute,
  AppProjectsIpRangeScannerRoute: AppProjectsIpRangeScannerRoute,
  AppProjectsPortScannerRoute: AppProjectsPortScannerRoute,
  AppProjectsSubdomainEnumerationRoute: AppProjectsSubdomainEnumerationRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
